### PR TITLE
Adds configuration option for uploading directory other than cwd

### PR DESCRIPTION
**Pull request by skaapgif**
@jamestalmage Please give some feedback on this. If you think it's worth including I can update the documentation to reflect these changes as part of this pull request.

Given a folder structure like:

```
aws-credentials.json
public/
public/index.html
public/images
public/images/logo.jpg
```

The following configuration file will upload the contents of `public` instead of uploading the whole folder.

```
module.exports = {
    credentials:"aws-credentials.json",
    bucketName:"example.com",
    directory: './public',
    patterns:[
        "**/*"
    ]
}
```

This is especially useful if you have a build folder and want everything in the build folder to be uploaded (`**/*`) but your s3-static-site-uploader configuration file isn't in the root of that build folder.

### CODE REVIEW

**Comment by jamestalmage** [comment]
Sounds like a good idea, but your implementation needs test coverage (and to pass the existing test suite).

**Comment by skaapgif** [comment]
Yeah I'll work on that and update this PR, just wanted to make sure you agree with the intention in principal.

**Comment by jamestalmage** [comment]
Cool.
(FYI: Always a good idea to open an issue before starting work on a PR)

**Comment by jamestalmage** [comment]
Also, pick something better than `directory`. `baseDir`, or `cwd` would work

**Comment by skaapgif** [comment]
Although it's not a very big feature, I wasn't able to finish it quickly enough to justify my needs. I've decided to rather use a gulp-based s3 uploading tool.

**Comment by jiarongxu** [comment]
@jamestalmage any plan to finish this?

**Comment by jamestalmage** [comment]
@jiarongxu - PR welcome.

**Pull request closed without merging**
